### ISSUE TITLE
Infinity/NaN

### ISSUE THREAD

**Issue by unrealiceyou** [KadTheHunter/ShulkerArchives#63]
Minecraft's JSON will just consider those strings. Infinity strings can be replaced with a valid (although pretty big) number. As for NaN though, well that is not gonna work. Maybe a different approach is needed

**Comment by KadTheHunter** [comment]
@unrealiceyou both are rather uncommon in the wider spread of kits (or so I believe), so I'm not super concerned. I can probably just preface the text file containing the NBT with a note about the Infinity/NaN when needed, including how to properly import it.

**Comment by KadTheHunter** [comment]
/remind me To test items involving this in 5 hours

**Comment by KadTheHunter** [comment]
Can confirm after testing that both `Infinity` and `NaN` just gets converted to `0.0`  when added to an item as SNBT, and has to be manually changed.

Ultimately it seems Infinity/NaN items can't be stored as SNBT at all without removing the Infinity/NaN.

Unless there's another way to save these items beyond SNBT.... they can't be saved.

**Comment by KadTheHunter** [comment]
What if we saved NaN/INF in Hotbars?

**Comment by KadTheHunter** [comment]
Can confirm, Hotbars work.

Any method involving SNBT will _**not**_ work, as SNBT causes NaN and Infinity to be reset to 0.0 when applied to an item.

My theory is when the SNBT gets converted to normal NBT, it can't map "NaN" or "Infinity", so resets it to default (0.0)

**Comment by KadTheHunter** [comment]
Closing this, as it's solved in the last few commits. NBT Editor allows loading of .nbt files, which store Infinity/NaN properly. Problem solved :D
